/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject.tang.chen;

import java.awt.Color;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author altan4377
 */
public class MakeSurvey extends javax.swing.JFrame {

    SelectSurvey previousWindow;
    Welcome firstWindow;
    Survey survey;
    File file;
    
    ArrayList<Question> questions;

    /**
     * Creates new form MakeSurvey
     */
    public MakeSurvey(SelectSurvey m) {
        initComponents();
        previousWindow = m;
        survey = new Survey();
        getContentPane().setBackground(new Color(153, 204, 255));
        txtQuestion.setText("");
        txtChoice1.setText("");
        txtChoice2.setText("");
        txtChoice3.setText("");
        txtChoice4.setText("");
        txtChoice5.setText("");
        txtChoice6.setText("");
        txtChoice7.setText("");
        txtChoice8.setText("");
        txtChoice9.setText("");
        txtChoice10.setText("");
        txtChoice11.setText("");
        txtChoice12.setText("");
        openFiles();
        questions = new ArrayList();
    }

    public void openFiles(){
        file = new File("src\\finalproject\\tang\\chen\\NewFile");
        
        try {
            if(file.createNewFile()){
//                System.out.println("FILE EXISTS");
            }else{
//                System.out.println("FILE CREATED");
            }
        } catch (IOException ex) {
            Logger.getLogger(MakeSurvey.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
//        try {
//            FileWriter fw = new FileWriter(file);
//            BufferedWriter bw = new BufferedWriter(fw);
//            bw.write("Hello. It's me");
//            bw.close();
//        } catch (IOException ex) {
//            Logger.getLogger(MakeSurvey.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDone = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblChoice1 = new javax.swing.JLabel();
        lblChoice2 = new javax.swing.JLabel();
        lblChoice3 = new javax.swing.JLabel();
        lblChoice4 = new javax.swing.JLabel();
        lblChoice5 = new javax.swing.JLabel();
        lblChoice6 = new javax.swing.JLabel();
        lblChoice7 = new javax.swing.JLabel();
        lblChoice8 = new javax.swing.JLabel();
        lblChoice9 = new javax.swing.JLabel();
        lblChoice10 = new javax.swing.JLabel();
        lblChoice11 = new javax.swing.JLabel();
        lblChoice12 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        txtChoice1 = new javax.swing.JTextField();
        txtChoice2 = new javax.swing.JTextField();
        txtChoice4 = new javax.swing.JTextField();
        txtChoice5 = new javax.swing.JTextField();
        txtChoice6 = new javax.swing.JTextField();
        txtChoice3 = new javax.swing.JTextField();
        txtChoice7 = new javax.swing.JTextField();
        txtChoice8 = new javax.swing.JTextField();
        txtChoice9 = new javax.swing.JTextField();
        txtChoice10 = new javax.swing.JTextField();
        txtChoice12 = new javax.swing.JTextField();
        txtChoice11 = new javax.swing.JTextField();
        cboType = new javax.swing.JComboBox();
        btnType = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnBackward = new javax.swing.JButton();
        btnForward = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        lblQNum = new javax.swing.JLabel();
        lblTotQuestions = new javax.swing.JLabel();
        txtQuestionNumber = new javax.swing.JTextField();
        txtTotQuestions = new javax.swing.JTextField();
        jspInstructions = new javax.swing.JScrollPane();
        txtInstructions = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        txtTitleSurvey = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Make The Survey");

        btnDone.setBackground(new java.awt.Color(255, 216, 26));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        lblQuestion.setText("Question:");

        lblType.setText("Type Of Question");

        lblChoice1.setText("Choice #1:");

        lblChoice2.setText("Choice #2:");

        lblChoice3.setText("Choice #3:");

        lblChoice4.setText("Choice #4:");

        lblChoice5.setText("Choice #5:");

        lblChoice6.setText("Choice #6:");

        lblChoice7.setText("Choice #7:");

        lblChoice8.setText("Choice #8:");

        lblChoice9.setText("Choice #9:");

        lblChoice10.setText("Choice #10:");

        lblChoice11.setText("Choice #11:");

        lblChoice12.setText("Choice #12:");

        cboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Response Multiple Choice", "Multiple Response Multiple Choice", "Short Answer" }));

        btnType.setBackground(new java.awt.Color(255, 212, 26));
        btnType.setText("Submit");
        btnType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTypeActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(255, 212, 26));
        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnBackward.setBackground(new java.awt.Color(255, 212, 26));
        btnBackward.setText("<");
        btnBackward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackwardActionPerformed(evt);
            }
        });

        btnForward.setBackground(new java.awt.Color(255, 212, 26));
        btnForward.setText(">");
        btnForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(255, 212, 26));
        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 212, 26));
        btnAdd.setText("Add This Question");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnModify.setBackground(new java.awt.Color(255, 212, 26));
        btnModify.setText("Modify This Question");

        lblQNum.setText("Question Number:");

        lblTotQuestions.setText("Total Number Of Questions:");

        txtQuestionNumber.setEditable(false);

        txtTotQuestions.setEditable(false);

        txtInstructions.setEditable(false);
        txtInstructions.setColumns(20);
        txtInstructions.setRows(5);
        txtInstructions.setText("To Create A Question:\n1. Select the type of question and click \"Submit\"\n2. Fill in the question and the possible choices. \nThe maximum number of choices is 12.\n3. Press \"Add This Question\" to register this question.\nYou can also modify the question by selecting the desired question\nand press \"Modify This Question\" once you commit these changes.\nTo save the survey you MUST press \"Done\".");
        jspInstructions.setViewportView(txtInstructions);

        lblTitle.setText("Title Of Survey");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblChoice1)
                        .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(lblChoice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblChoice12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChoice2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice12, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice11, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice7, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice8, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice9, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice5, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice6, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnType))
                    .addComponent(txtChoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoice10, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitleSurvey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDone)
                            .addComponent(btnModify)
                            .addComponent(btnAdd)
                            .addComponent(btnLast)
                            .addComponent(btnForward)
                            .addComponent(btnFirst)
                            .addComponent(btnBackward))
                        .addGap(221, 221, 221))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQNum)
                                    .addComponent(lblTotQuestions))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuestionNumber)
                                    .addComponent(txtTotQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jspInstructions))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jspInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQNum)
                            .addComponent(txtQuestionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotQuestions)
                            .addComponent(txtTotQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFirst)
                        .addGap(18, 18, 18)
                        .addComponent(btnBackward)
                        .addGap(18, 18, 18)
                        .addComponent(btnForward)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast)
                        .addGap(26, 26, 26)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnModify)
                        .addGap(18, 18, 18)
                        .addComponent(btnDone))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(txtTitleSurvey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuestion)
                            .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnType)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice1)
                            .addComponent(txtChoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice2)
                            .addComponent(txtChoice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChoice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChoice3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice4)
                            .addComponent(txtChoice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice5)
                            .addComponent(txtChoice5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice6)
                            .addComponent(txtChoice6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice7)
                            .addComponent(txtChoice7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice8)
                            .addComponent(txtChoice8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice9)
                            .addComponent(txtChoice9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice10)
                            .addComponent(txtChoice10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice11)
                            .addComponent(txtChoice11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice12)
                            .addComponent(txtChoice12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        if (firstWindow == null) {
            firstWindow = new Welcome();
        }

        firstWindow.setVisible(true);
        this.setVisible(false);
        
        
        
        String preProcessTitle = txtTitleSurvey.getText();
        String postProcessTitle = "";
        for(int i = 0; i < preProcessTitle.length(); i++){
            if((int)(preProcessTitle.charAt(i)) == 32){
                postProcessTitle  = postProcessTitle + " ";
            }else if((int)(preProcessTitle.charAt(i)) >= 65 && (int)(preProcessTitle.charAt(i)) <= 90){
                postProcessTitle  = postProcessTitle + preProcessTitle.charAt(i);
            }else if((int)(preProcessTitle.charAt(i)) >= 97 && (int)(preProcessTitle.charAt(i)) <= 122){
                postProcessTitle  = postProcessTitle + preProcessTitle.charAt(i);
            }
        }
        
        
        String fileName = "src\\finalproject\\tang\\chen\\" + postProcessTitle;
        
        File file2 = new File(fileName);
        
        file.renameTo(file2);
        
        ArrayList<String> whatIsThere = new ArrayList();
        try{
            FileReader fr = new FileReader("src\\finalproject\\tang\\chen\\SurveyStorage");
            BufferedReader br = new BufferedReader(fr);
            boolean eof = false;
            while(!eof){
                String line = br.readLine();
                if(line == null){
                    eof = true;
                }else{
                    whatIsThere.add(line);
                }
            }
            br.close();
        }catch(IOException e){
            System.out.println("ERROR " + e);
        }
        
        try {
            FileWriter fw = new FileWriter("src\\finalproject\\tang\\chen\\SurveyStorage");
            BufferedWriter bw = new BufferedWriter(fw);
            for(int i = 0; i < whatIsThere.size(); i++){
                bw.write(whatIsThere.get(i) + "\n");
            }
            bw.write(preProcessTitle); //When this writes everything is gone. Have to find a way to only add not subtract
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(MakeSurvey.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        txtQuestionNumber.setText("0");
        txtQuestion.setText(((survey.getSurveyQuestions()).get(0)).getQuestion());
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackwardActionPerformed
        int currentQNumber = Integer.parseInt(txtQuestionNumber.getText());
        txtQuestionNumber.setText((currentQNumber - 1) + "");
    }//GEN-LAST:event_btnBackwardActionPerformed

    private void btnForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardActionPerformed
        int currentQNumber = Integer.parseInt(txtQuestionNumber.getText());
        txtQuestionNumber.setText((currentQNumber + 1) + "");
    }//GEN-LAST:event_btnForwardActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        txtQuestionNumber.setText("size of array - 1");
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTypeActionPerformed
        String typeQuestion = cboType.getSelectedItem().toString();
        if (typeQuestion.equals("Single Response Multiple Choice") || typeQuestion.equals("Multiple Response Multiple Choice")) {
            txtChoice1.setEditable(true);
            txtChoice2.setEditable(true);
            txtChoice3.setEditable(true);
            txtChoice4.setEditable(true);
            txtChoice5.setEditable(true);
            txtChoice6.setEditable(true);
            txtChoice7.setEditable(true);
            txtChoice8.setEditable(true);
            txtChoice9.setEditable(true);
            txtChoice10.setEditable(true);
            txtChoice11.setEditable(true);
            txtChoice12.setEditable(true);
        } else {
            txtChoice1.setEditable(false);
            txtChoice2.setEditable(false);
            txtChoice3.setEditable(false);
            txtChoice4.setEditable(false);
            txtChoice5.setEditable(false);
            txtChoice6.setEditable(false);
            txtChoice7.setEditable(false);
            txtChoice8.setEditable(false);
            txtChoice9.setEditable(false);
            txtChoice10.setEditable(false);
            txtChoice11.setEditable(false);
            txtChoice12.setEditable(false);
            txtChoice1.setBackground(Color.gray);
            txtChoice2.setBackground(Color.gray);
            txtChoice3.setBackground(Color.gray);
            txtChoice4.setBackground(Color.gray);
            txtChoice5.setBackground(Color.gray);
            txtChoice6.setBackground(Color.gray);
            txtChoice7.setBackground(Color.gray);
            txtChoice8.setBackground(Color.gray);
            txtChoice9.setBackground(Color.gray);
            txtChoice10.setBackground(Color.gray);
            txtChoice11.setBackground(Color.gray);
            txtChoice12.setBackground(Color.gray);
        }

    }//GEN-LAST:event_btnTypeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Question newQuestion = null;
        try {
            FileWriter fw = new FileWriter(file, true); //the true will append the new data
            BufferedWriter bw = new BufferedWriter(fw);
            String typeQuestion = cboType.getSelectedItem().toString();
            bw.write(typeQuestion + "\n"); 
            String question = txtQuestion.getText();
            bw.write(question + "\n");//appends the string to the file
            if (typeQuestion.equals("Single Response Multiple Choice")){
                bw.write(txtChoice1.getText() + ", ");
                bw.write(txtChoice2.getText() + ", ");
                bw.write(txtChoice3.getText() + ", ");
                bw.write(txtChoice4.getText() + ", ");
                bw.write(txtChoice5.getText() + ", ");
                bw.write(txtChoice6.getText() + ", ");
                bw.write(txtChoice7.getText() + ", ");
                bw.write(txtChoice8.getText() + ", ");
                bw.write(txtChoice9.getText() + ", ");
                bw.write(txtChoice10.getText() + ", ");
                bw.write(txtChoice11.getText() + ", ");
                bw.write(txtChoice12.getText() + "\n");
                ArrayList<String> answers = new ArrayList();
                answers.add(txtChoice1.getText());
                answers.add(txtChoice2.getText());
                answers.add(txtChoice3.getText());
                answers.add(txtChoice4.getText());
                answers.add(txtChoice5.getText());
                answers.add(txtChoice6.getText());
                answers.add(txtChoice7.getText());
                answers.add(txtChoice8.getText());
                answers.add(txtChoice9.getText());
                answers.add(txtChoice10.getText());
                answers.add(txtChoice11.getText());
                answers.add(txtChoice12.getText());
                newQuestion = new SingleMC(question,answers);
//                survey.getSurveyQuestions().add(newQuestion);
            }else if(typeQuestion.equals("Multiple Response Multiple Choice")){
                bw.write(txtChoice1.getText() + ", ");
                bw.write(txtChoice2.getText() + ", ");
                bw.write(txtChoice3.getText() + ", ");
                bw.write(txtChoice4.getText() + ", ");
                bw.write(txtChoice5.getText() + ", ");
                bw.write(txtChoice6.getText() + ", ");
                bw.write(txtChoice7.getText() + ", ");
                bw.write(txtChoice8.getText() + ", ");
                bw.write(txtChoice9.getText() + ", ");
                bw.write(txtChoice10.getText() + ", ");
                bw.write(txtChoice11.getText() + ", ");
                bw.write(txtChoice12.getText() + "\n");
                ArrayList<String> answers = new ArrayList();
                answers.add(txtChoice1.getText());
                answers.add(txtChoice2.getText());
                answers.add(txtChoice3.getText());
                answers.add(txtChoice4.getText());
                answers.add(txtChoice5.getText());
                answers.add(txtChoice6.getText());
                answers.add(txtChoice7.getText());
                answers.add(txtChoice8.getText());
                answers.add(txtChoice9.getText());
                answers.add(txtChoice10.getText());
                answers.add(txtChoice11.getText());
                answers.add(txtChoice12.getText());
                newQuestion = new MultipleMC(question,answers);
//                (survey.getSurveyQuestions()).add(new MultipleMC(question,answers));
            }else{
//                (survey.getSurveyQuestions()).add(new ShortAnswer(question));
                newQuestion = new ShortAnswer(question);
                bw.write("Short answer question. Choices do not apply");
            }
            bw.close();
        } catch (IOException ioe) {
            System.err.println("IOException: " + ioe.getMessage());
        }
        questions.add(newQuestion);
        txtQuestion.setText("");
        txtChoice1.setText("");
        txtChoice2.setText("");
        txtChoice3.setText("");
        txtChoice4.setText("");
        txtChoice5.setText("");
        txtChoice6.setText("");
        txtChoice7.setText("");
        txtChoice8.setText("");
        txtChoice9.setText("");
        txtChoice10.setText("");
        txtChoice11.setText("");
        txtChoice12.setText("");
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackward;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnForward;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnType;
    private javax.swing.JComboBox cboType;
    private javax.swing.JScrollPane jspInstructions;
    private javax.swing.JLabel lblChoice1;
    private javax.swing.JLabel lblChoice10;
    private javax.swing.JLabel lblChoice11;
    private javax.swing.JLabel lblChoice12;
    private javax.swing.JLabel lblChoice2;
    private javax.swing.JLabel lblChoice3;
    private javax.swing.JLabel lblChoice4;
    private javax.swing.JLabel lblChoice5;
    private javax.swing.JLabel lblChoice6;
    private javax.swing.JLabel lblChoice7;
    private javax.swing.JLabel lblChoice8;
    private javax.swing.JLabel lblChoice9;
    private javax.swing.JLabel lblQNum;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotQuestions;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtChoice1;
    private javax.swing.JTextField txtChoice10;
    private javax.swing.JTextField txtChoice11;
    private javax.swing.JTextField txtChoice12;
    private javax.swing.JTextField txtChoice2;
    private javax.swing.JTextField txtChoice3;
    private javax.swing.JTextField txtChoice4;
    private javax.swing.JTextField txtChoice5;
    private javax.swing.JTextField txtChoice6;
    private javax.swing.JTextField txtChoice7;
    private javax.swing.JTextField txtChoice8;
    private javax.swing.JTextField txtChoice9;
    private javax.swing.JTextArea txtInstructions;
    private javax.swing.JTextField txtQuestion;
    private javax.swing.JTextField txtQuestionNumber;
    private javax.swing.JTextField txtTitleSurvey;
    private javax.swing.JTextField txtTotQuestions;
    // End of variables declaration//GEN-END:variables
}
