/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package finalproject.tang.chen;

/**
 *
 * @author altan4377
 */
public class MultipleResponseMultipleChoice extends javax.swing.JFrame {

    /**
     * Creates new form MultipleResponseMultipleChoice
     */
    public MultipleResponseMultipleChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        ckbChoice1 = new javax.swing.JCheckBox();
        ckbChoice2 = new javax.swing.JCheckBox();
        ckbChoice3 = new javax.swing.JCheckBox();
        ckbChoice4 = new javax.swing.JCheckBox();
        ckbChoice5 = new javax.swing.JCheckBox();
        ckbChoice6 = new javax.swing.JCheckBox();
        ckbChoice7 = new javax.swing.JCheckBox();
        ckbChoice8 = new javax.swing.JCheckBox();
        ckbChoice9 = new javax.swing.JCheckBox();
        ckbChoice10 = new javax.swing.JCheckBox();
        ckbChoice11 = new javax.swing.JCheckBox();
        ckbChoice12 = new javax.swing.JCheckBox();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ckbChoice1.setText("Choice Not Available..");

        ckbChoice2.setText("Choice Not Available..");

        ckbChoice3.setText("Choice Not Available..");

        ckbChoice4.setText("Choice Not Available..");

        ckbChoice5.setText("Choice Not Available..");

        ckbChoice6.setText("Choice Not Available..");

        ckbChoice7.setText("Choice Not Available..");

        ckbChoice8.setText("Choice Not Available..");

        ckbChoice9.setText("Choice Not Available..");

        ckbChoice10.setText("Choice Not Available..");

        ckbChoice11.setText("Choice Not Available..");

        ckbChoice12.setText("Choice Not Available..");

        btnSelect.setText("Next Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbChoice10)
                    .addComponent(ckbChoice12)
                    .addComponent(ckbChoice11)
                    .addComponent(ckbChoice9)
                    .addComponent(ckbChoice8)
                    .addComponent(ckbChoice7)
                    .addComponent(ckbChoice6)
                    .addComponent(ckbChoice4)
                    .addComponent(ckbChoice3)
                    .addComponent(ckbChoice2)
                    .addComponent(ckbChoice1)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbChoice5)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelect)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ckbChoice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbChoice5)
                    .addComponent(btnSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice10)
                .addGap(3, 3, 3)
                .addComponent(ckbChoice11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbChoice12)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelect;
    private javax.swing.JCheckBox ckbChoice1;
    private javax.swing.JCheckBox ckbChoice10;
    private javax.swing.JCheckBox ckbChoice11;
    private javax.swing.JCheckBox ckbChoice12;
    private javax.swing.JCheckBox ckbChoice2;
    private javax.swing.JCheckBox ckbChoice3;
    private javax.swing.JCheckBox ckbChoice4;
    private javax.swing.JCheckBox ckbChoice5;
    private javax.swing.JCheckBox ckbChoice6;
    private javax.swing.JCheckBox ckbChoice7;
    private javax.swing.JCheckBox ckbChoice8;
    private javax.swing.JCheckBox ckbChoice9;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
