/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package finalproject.tang.chen;

/**
 *
 * @author altan4377
 */
public class SingleResponseMultipleChoice extends javax.swing.JFrame {

    /**
     * Creates new form SingleResponseMultipleChoice
     */
    public SingleResponseMultipleChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblQuestion = new javax.swing.JLabel();
        btnChoice1 = new javax.swing.JRadioButton();
        btnChoice2 = new javax.swing.JRadioButton();
        btnChoice3 = new javax.swing.JRadioButton();
        btnChoice4 = new javax.swing.JRadioButton();
        btnChoice5 = new javax.swing.JRadioButton();
        btnChoice6 = new javax.swing.JRadioButton();
        btnChoice7 = new javax.swing.JRadioButton();
        btnChoice8 = new javax.swing.JRadioButton();
        btnChoice9 = new javax.swing.JRadioButton();
        btnChoice10 = new javax.swing.JRadioButton();
        btnChoice11 = new javax.swing.JRadioButton();
        brnChoice12 = new javax.swing.JRadioButton();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(btnChoice1);
        btnChoice1.setText("No Responses Available..");

        buttonGroup1.add(btnChoice2);
        btnChoice2.setText("No Responses Available..");

        buttonGroup1.add(btnChoice3);
        btnChoice3.setText("No Responses Available..");

        buttonGroup1.add(btnChoice4);
        btnChoice4.setText("No Responses Available..");

        buttonGroup1.add(btnChoice5);
        btnChoice5.setText("No Responses Available..");

        buttonGroup1.add(btnChoice6);
        btnChoice6.setText("No Responses Available..");

        buttonGroup1.add(btnChoice7);
        btnChoice7.setText("No Responses Available..");

        buttonGroup1.add(btnChoice8);
        btnChoice8.setText("No Responses Available..");

        buttonGroup1.add(btnChoice9);
        btnChoice9.setText("No Responses Available..");

        buttonGroup1.add(btnChoice10);
        btnChoice10.setText("No Responses Available..");

        buttonGroup1.add(btnChoice11);
        btnChoice11.setText("No Responses Available..");

        buttonGroup1.add(brnChoice12);
        brnChoice12.setText("No Responses Available..");

        btnSelect.setText("Next Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChoice2)
                            .addComponent(btnChoice1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChoice3)
                                .addGap(70, 70, 70)
                                .addComponent(btnSelect))
                            .addComponent(btnChoice4)
                            .addComponent(btnChoice5)
                            .addComponent(btnChoice6)
                            .addComponent(btnChoice7)
                            .addComponent(btnChoice8)
                            .addComponent(btnChoice9)
                            .addComponent(btnChoice10)
                            .addComponent(btnChoice11)
                            .addComponent(brnChoice12))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChoice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChoice3)
                    .addComponent(btnSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChoice11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brnChoice12)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton brnChoice12;
    private javax.swing.JRadioButton btnChoice1;
    private javax.swing.JRadioButton btnChoice10;
    private javax.swing.JRadioButton btnChoice11;
    private javax.swing.JRadioButton btnChoice2;
    private javax.swing.JRadioButton btnChoice3;
    private javax.swing.JRadioButton btnChoice4;
    private javax.swing.JRadioButton btnChoice5;
    private javax.swing.JRadioButton btnChoice6;
    private javax.swing.JRadioButton btnChoice7;
    private javax.swing.JRadioButton btnChoice8;
    private javax.swing.JRadioButton btnChoice9;
    private javax.swing.JButton btnSelect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
